// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastracture.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260120042528_edit_table_years")]
    partial class edittableyears
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Constant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Constants");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "تلفن",
                            Type = 0
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "ایمیل",
                            Type = 1
                        },
                        new
                        {
                            Id = 3L,
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "آدرس",
                            Type = 2
                        },
                        new
                        {
                            Id = 4L,
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "تعداد دفعات مجاز برای ورود ناموفق",
                            Type = 3,
                            Value = "5"
                        },
                        new
                        {
                            Id = 5L,
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "اجبار تغییر کلمه عبور کاربر بعد از چند روز؟",
                            Type = 4,
                            Value = "60"
                        },
                        new
                        {
                            Id = 6L,
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "تعداد کاراکتر های تکراری مجاز در تغییر کلمه عبور",
                            Type = 5,
                            Value = "4"
                        },
                        new
                        {
                            Id = 7L,
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "چک کردن تکراری نبودن پسورد با دو یا سه پسورد قدیم",
                            Type = 6,
                            Value = "3"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Days", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("SortName")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("Domain.Entities.FoodManage.DiningHall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("HallCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrgId")
                        .HasColumnType("int");

                    b.Property<string>("OrgTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("PersonalTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalTypeId");

                    b.ToTable("DiningHall");
                });

            modelBuilder.Entity("Domain.Entities.FoodManage.FoodTypes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("SortName")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodTypes");
                });

            modelBuilder.Entity("Domain.Entities.FoodManage.Foods", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FoodTypesId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodTypesId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Domain.Entities.FoodManage.Kitchens", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CookingCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrgId")
                        .HasColumnType("int");

                    b.Property<string>("OrgTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kitchens");
                });

            modelBuilder.Entity("Domain.Entities.FoodPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrganId")
                        .HasColumnType("int");

                    b.Property<string>("OrganTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint");

                    b.Property<long>("YearsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("YearsId");

                    b.ToTable("FoodPlan");
                });

            modelBuilder.Entity("Domain.Entities.FoodPlanDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DayId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FoodDesserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FoodDorchinId")
                        .HasColumnType("bigint");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.Property<long>("FoodPlanId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("MealId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("FoodId");

                    b.HasIndex("FoodPlanId");

                    b.HasIndex("MealId");

                    b.ToTable("FoodPlanDay");
                });

            modelBuilder.Entity("Domain.Entities.FoodReservation.FoodReserve", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FoodReserves");
                });

            modelBuilder.Entity("Domain.Entities.FoodReservation.FoodReserveDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DayId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DessertId")
                        .HasColumnType("bigint");

                    b.Property<long>("FoodReserveId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MainFoodId")
                        .HasColumnType("bigint");

                    b.Property<long>("MealId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SideDishId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("DessertId");

                    b.HasIndex("FoodReserveId");

                    b.HasIndex("MainFoodId");

                    b.HasIndex("MealId");

                    b.HasIndex("SideDishId");

                    b.ToTable("FoodReserveDetails");
                });

            modelBuilder.Entity("Domain.Entities.FoodSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<double>("PercentBreakfast")
                        .HasColumnType("float");

                    b.Property<double>("PercentDinner")
                        .HasColumnType("float");

                    b.Property<double>("PercentLunch")
                        .HasColumnType("float");

                    b.Property<long>("PersonalTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("YeganTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PersonalTypeId");

                    b.HasIndex("YeganTypeId");

                    b.ToTable("FoodSource");
                });

            modelBuilder.Entity("Domain.Entities.Garrison.OrganGarrison", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstedadKadr")
                        .HasColumnType("int");

                    b.Property<int>("EstedadVazife")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrgId")
                        .HasColumnType("int");

                    b.Property<long>("OrganGarrisonTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SortName")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganGarrisonTypeId");

                    b.HasIndex("ParentId");

                    b.ToTable("OrganGarrison");
                });

            modelBuilder.Entity("Domain.Entities.Garrison.OrganGarrisonType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<long?>("DaysId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("MealId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SortName")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DaysId");

                    b.HasIndex("MealId");

                    b.ToTable("OrganGarrisonType");
                });

            modelBuilder.Entity("Domain.Entities.Garrison.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("NationalCode")
                        .HasColumnType("int");

                    b.Property<long>("OrganGarrisonId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PersonCode")
                        .HasColumnType("int");

                    b.Property<long>("PersonTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PersonalTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganGarrisonId");

                    b.HasIndex("PersonalTypeId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Domain.Entities.LogSystem.SeriLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SeriLog");
                });

            modelBuilder.Entity("Domain.Entities.Meal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("SortName")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Meal");
                });

            modelBuilder.Entity("Domain.Entities.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("HasLink")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeedReAuthorize")
                        .HasColumnType("bit");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ShowInMenu")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Action = "index",
                            Area = "admin",
                            Controller = "dashboard",
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLink = true,
                            IsDeleted = false,
                            IsEnabled = true,
                            MaterialIcon = "dashboard",
                            NeedReAuthorize = false,
                            ShowInMenu = true,
                            Sort = 1,
                            Title = "داشبورد"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLink = false,
                            IsDeleted = false,
                            IsEnabled = true,
                            MaterialIcon = "account_circle",
                            NeedReAuthorize = false,
                            ShowInMenu = true,
                            Sort = 7,
                            Title = "امکانات مدیریتی"
                        },
                        new
                        {
                            Id = 3L,
                            Action = "index",
                            Area = "authsystem",
                            Controller = "users",
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLink = true,
                            IsDeleted = false,
                            IsEnabled = true,
                            NeedReAuthorize = false,
                            ParentId = 2L,
                            ShowInMenu = true,
                            Sort = 1,
                            Title = "کاربران"
                        },
                        new
                        {
                            Id = 4L,
                            Action = "index",
                            Area = "authsystem",
                            Controller = "menus",
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLink = true,
                            IsDeleted = false,
                            IsEnabled = true,
                            NeedReAuthorize = false,
                            ParentId = 2L,
                            ShowInMenu = true,
                            Sort = 2,
                            Title = "منو ها"
                        },
                        new
                        {
                            Id = 5L,
                            Action = "index",
                            Area = "authsystem",
                            Controller = "roles",
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLink = true,
                            IsDeleted = false,
                            IsEnabled = true,
                            NeedReAuthorize = false,
                            ParentId = 2L,
                            ShowInMenu = true,
                            Sort = 3,
                            Title = "نقش ها"
                        },
                        new
                        {
                            Id = 10L,
                            Action = "index",
                            Area = "shared",
                            Controller = "constants",
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLink = true,
                            IsDeleted = false,
                            IsEnabled = true,
                            NeedReAuthorize = false,
                            ParentId = 2L,
                            ShowInMenu = true,
                            Sort = 4,
                            Title = "تنظیمات"
                        },
                        new
                        {
                            Id = 6L,
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLink = false,
                            IsDeleted = false,
                            IsEnabled = true,
                            MaterialIcon = "assignment",
                            NeedReAuthorize = false,
                            ShowInMenu = true,
                            Sort = 10,
                            Title = "لاگ ها"
                        },
                        new
                        {
                            Id = 7L,
                            Action = "index",
                            Area = "logsystem",
                            Controller = "smslogs",
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLink = true,
                            IsDeleted = false,
                            IsEnabled = true,
                            NeedReAuthorize = false,
                            ParentId = 6L,
                            ShowInMenu = true,
                            Sort = 1,
                            Title = "پیام های ارسالی"
                        },
                        new
                        {
                            Id = 8L,
                            Action = "index",
                            Area = "logsystem",
                            Controller = "loginlogs",
                            CreateDate = new DateTime(2022, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLink = true,
                            IsDeleted = false,
                            IsEnabled = true,
                            NeedReAuthorize = false,
                            ParentId = 6L,
                            ShowInMenu = true,
                            Sort = 3,
                            Title = "ورود و خروج کاربران"
                        },
                        new
                        {
                            Id = 9L,
                            Action = "index",
                            Area = "logsystem",
                            Controller = "actionlogs",
                            CreateDate = new DateTime(2022, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLink = true,
                            IsDeleted = false,
                            IsEnabled = true,
                            NeedReAuthorize = false,
                            ParentId = 6L,
                            ShowInMenu = true,
                            Sort = 4,
                            Title = "عملیات کاربران"
                        });
                });

            modelBuilder.Entity("Domain.Entities.PersonalType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("SortName")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PersonalType");
                });

            modelBuilder.Entity("Domain.Entities.QoutaAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DayId")
                        .HasColumnType("bigint");

                    b.Property<string>("DayTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("FoodPlanDayId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("MealId")
                        .HasColumnType("bigint");

                    b.Property<string>("MealTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("OrgId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrgTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("OrganGarrisonId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("QoutaAllocationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("FoodPlanDayId");

                    b.HasIndex("MealId");

                    b.HasIndex("OrganGarrisonId");

                    b.ToTable("QoutaAllocations");
                });

            modelBuilder.Entity("Domain.Entities.QoutaPerson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrgId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrgTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("OrganGarrisonId")
                        .HasColumnType("bigint");

                    b.Property<string>("PersonalCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("PersonalTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("QoutaAllocationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganGarrisonId");

                    b.HasIndex("PersonalTypeId");

                    b.HasIndex("QoutaAllocationId");

                    b.ToTable("QoutaPersons");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEnabled = true,
                            Title = "ادمین کل"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RoleMenu", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleMenus");

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            MenuId = 1L
                        },
                        new
                        {
                            RoleId = 1L,
                            MenuId = 2L
                        },
                        new
                        {
                            RoleId = 1L,
                            MenuId = 3L
                        },
                        new
                        {
                            RoleId = 1L,
                            MenuId = 4L
                        },
                        new
                        {
                            RoleId = 1L,
                            MenuId = 5L
                        },
                        new
                        {
                            RoleId = 1L,
                            MenuId = 6L
                        },
                        new
                        {
                            RoleId = 1L,
                            MenuId = 7L
                        },
                        new
                        {
                            RoleId = 1L,
                            MenuId = 8L
                        },
                        new
                        {
                            RoleId = 1L,
                            MenuId = 9L
                        },
                        new
                        {
                            RoleId = 1L,
                            MenuId = 10L
                        });
                });

            modelBuilder.Entity("Domain.Entities.Season", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("SortName")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Season");
                });

            modelBuilder.Entity("Domain.Entities.Statistic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("OfficerCount")
                        .HasColumnType("int");

                    b.Property<long>("OrganGarrisonId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SolidierCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganGarrisonId");

                    b.ToTable("Statistic");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ChangePasswordCycle")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastEditUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OmdOrgId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("PasswordIsChanged")
                        .HasColumnType("bit");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RegUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsEnabled = true,
                            Mobile = "09123456789",
                            Name = "ادمین",
                            OmdOrgId = 0,
                            Password = "??+c???V????????????	????{\\8???O??Zn1JM??W?N?O\n????>??ix",
                            PasswordIsChanged = false,
                            RoleId = 1L,
                            Type = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserPasswordHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ExpPassword")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("StatusSave")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserPasswordHistorys");
                });

            modelBuilder.Entity("Domain.Entities.Years", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortName")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.ToTable("Years");
                });

            modelBuilder.Entity("Domain.Entities.YeganType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("SortName")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("YeganType");
                });

            modelBuilder.Entity("Domain.Entities.FoodManage.DiningHall", b =>
                {
                    b.HasOne("Domain.Entities.PersonalType", "PersonalType")
                        .WithMany("DiningHall")
                        .HasForeignKey("PersonalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonalType");
                });

            modelBuilder.Entity("Domain.Entities.FoodManage.Foods", b =>
                {
                    b.HasOne("Domain.Entities.FoodManage.FoodTypes", "FoodTypes")
                        .WithMany("Foods")
                        .HasForeignKey("FoodTypesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FoodTypes");
                });

            modelBuilder.Entity("Domain.Entities.FoodPlan", b =>
                {
                    b.HasOne("Domain.Entities.Season", "Season")
                        .WithMany("FoodPlan")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Years", "Years")
                        .WithMany("FoodPlan")
                        .HasForeignKey("YearsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Years");
                });

            modelBuilder.Entity("Domain.Entities.FoodPlanDay", b =>
                {
                    b.HasOne("Domain.Entities.Days", "Day")
                        .WithMany("FoodPlanDay")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FoodManage.Foods", "Food")
                        .WithMany("FoodPlanDay")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FoodPlan", "FoodPlan")
                        .WithMany("FoodPlanDay")
                        .HasForeignKey("FoodPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Meal", "Meal")
                        .WithMany("FoodPlanDay")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Food");

                    b.Navigation("FoodPlan");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Domain.Entities.FoodReservation.FoodReserveDetail", b =>
                {
                    b.HasOne("Domain.Entities.Days", "Day")
                        .WithMany()
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FoodManage.Foods", "Dessert")
                        .WithMany()
                        .HasForeignKey("DessertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.FoodReservation.FoodReserve", "FoodReserve")
                        .WithMany("Details")
                        .HasForeignKey("FoodReserveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FoodManage.Foods", "MainFood")
                        .WithMany()
                        .HasForeignKey("MainFoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FoodManage.Foods", "SideDish")
                        .WithMany()
                        .HasForeignKey("SideDishId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Day");

                    b.Navigation("Dessert");

                    b.Navigation("FoodReserve");

                    b.Navigation("MainFood");

                    b.Navigation("Meal");

                    b.Navigation("SideDish");
                });

            modelBuilder.Entity("Domain.Entities.FoodSource", b =>
                {
                    b.HasOne("Domain.Entities.PersonalType", "PersonalType")
                        .WithMany("FoodSource")
                        .HasForeignKey("PersonalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.YeganType", "YeganType")
                        .WithMany("FoodSource")
                        .HasForeignKey("YeganTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonalType");

                    b.Navigation("YeganType");
                });

            modelBuilder.Entity("Domain.Entities.Garrison.OrganGarrison", b =>
                {
                    b.HasOne("Domain.Entities.Garrison.OrganGarrisonType", "OrganGarrisonType")
                        .WithMany("OrganGarrisons")
                        .HasForeignKey("OrganGarrisonTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Garrison.OrganGarrison", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrganGarrisonType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.Garrison.OrganGarrisonType", b =>
                {
                    b.HasOne("Domain.Entities.Days", null)
                        .WithMany("QoutaAllocation")
                        .HasForeignKey("DaysId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Meal", null)
                        .WithMany("QoutaAllocations")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.Garrison.Person", b =>
                {
                    b.HasOne("Domain.Entities.Garrison.OrganGarrison", "OrganGarrison")
                        .WithMany("Person")
                        .HasForeignKey("OrganGarrisonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PersonalType", "PersonalType")
                        .WithMany()
                        .HasForeignKey("PersonalTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrganGarrison");

                    b.Navigation("PersonalType");
                });

            modelBuilder.Entity("Domain.Entities.Menu", b =>
                {
                    b.HasOne("Domain.Entities.Menu", "Parent")
                        .WithMany("SubMenus")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.QoutaAllocation", b =>
                {
                    b.HasOne("Domain.Entities.Days", "Day")
                        .WithMany()
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FoodPlanDay", "FoodPlanDay")
                        .WithMany("QoutaAllocations")
                        .HasForeignKey("FoodPlanDayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Garrison.OrganGarrison", "OrganGarrison")
                        .WithMany()
                        .HasForeignKey("OrganGarrisonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Day");

                    b.Navigation("FoodPlanDay");

                    b.Navigation("Meal");

                    b.Navigation("OrganGarrison");
                });

            modelBuilder.Entity("Domain.Entities.QoutaPerson", b =>
                {
                    b.HasOne("Domain.Entities.Garrison.OrganGarrison", null)
                        .WithMany("QoutaPerson")
                        .HasForeignKey("OrganGarrisonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.PersonalType", "PersonalType")
                        .WithMany("QoutaPersons")
                        .HasForeignKey("PersonalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.QoutaAllocation", "QoutaAllocation")
                        .WithMany("QoutaPerson")
                        .HasForeignKey("QoutaAllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonalType");

                    b.Navigation("QoutaAllocation");
                });

            modelBuilder.Entity("Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("Domain.Entities.Menu", "Menu")
                        .WithMany("Roles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Menus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Statistic", b =>
                {
                    b.HasOne("Domain.Entities.Garrison.OrganGarrison", "OrganGarrison")
                        .WithMany()
                        .HasForeignKey("OrganGarrisonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganGarrison");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Days", b =>
                {
                    b.Navigation("FoodPlanDay");

                    b.Navigation("QoutaAllocation");
                });

            modelBuilder.Entity("Domain.Entities.FoodManage.FoodTypes", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("Domain.Entities.FoodManage.Foods", b =>
                {
                    b.Navigation("FoodPlanDay");
                });

            modelBuilder.Entity("Domain.Entities.FoodPlan", b =>
                {
                    b.Navigation("FoodPlanDay");
                });

            modelBuilder.Entity("Domain.Entities.FoodPlanDay", b =>
                {
                    b.Navigation("QoutaAllocations");
                });

            modelBuilder.Entity("Domain.Entities.FoodReservation.FoodReserve", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Domain.Entities.Garrison.OrganGarrison", b =>
                {
                    b.Navigation("Person");

                    b.Navigation("QoutaPerson");
                });

            modelBuilder.Entity("Domain.Entities.Garrison.OrganGarrisonType", b =>
                {
                    b.Navigation("OrganGarrisons");
                });

            modelBuilder.Entity("Domain.Entities.Meal", b =>
                {
                    b.Navigation("FoodPlanDay");

                    b.Navigation("QoutaAllocations");
                });

            modelBuilder.Entity("Domain.Entities.Menu", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("Domain.Entities.PersonalType", b =>
                {
                    b.Navigation("DiningHall");

                    b.Navigation("FoodSource");

                    b.Navigation("QoutaPersons");
                });

            modelBuilder.Entity("Domain.Entities.QoutaAllocation", b =>
                {
                    b.Navigation("QoutaPerson");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Season", b =>
                {
                    b.Navigation("FoodPlan");
                });

            modelBuilder.Entity("Domain.Entities.Years", b =>
                {
                    b.Navigation("FoodPlan");
                });

            modelBuilder.Entity("Domain.Entities.YeganType", b =>
                {
                    b.Navigation("FoodSource");
                });
#pragma warning restore 612, 618
        }
    }
}
